resources:
  containers:
  - container: dotnetcore_arm
    image: huangtingluo/azure-pipelines-agent-eng:arm
  
  - container: dotnetcore_centos6
    image: huangtingluo/azure-pipelines-agent-eng:centos6

jobs:

################################################################################
- job: build_linux_x64_agent
################################################################################
  displayName: Linux Agent (x64)
  pool:
    name: Hosted Ubuntu 1604
  steps:

  # Steps template for non-windows platform
  - template: .vsts.template.nonwindows.yml
    parameters:
      componentDetection: 'false'

  # Create agent package zip
  - script: ./dev.sh package Release
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Upload agent package zip as build artifact
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact (Linux x64)
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      pathToPublish: _package
      artifactName: agent
      artifactType: container

